
name: MY-FIRST-ACTION

on:
  push:
    branches:
      - master
    
jobs:
  testing_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: string HELLO WORLD from t
      run: Echo "Hello, world! from testing"
       
  deploy_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: string HELLO WORLD from d
      run: echo Hello world from deploy  
